import { apiClient } from "@/lib/api-client";
import { uploadToCloudinary } from "@/lib/upload";
import type { Favorite } from "@/types/wishbook";

export type CreateFavoritePayload = Omit<
  Favorite,
  "id" | "userId" | "createdAt"
> & {
  // createdAt is generated by backend; we don't send it
  createdAt?: never;
};

export async function createFavorite(
  payload: CreateFavoritePayload,
): Promise<Favorite> {
  const body = {
    categoryId: payload.categoryId,
    title: payload.title,
    image: payload.image,
    rating: payload.rating,
    mood: payload.mood,
    whyILike: payload.whyILike,
    timePeriod: payload.timePeriod,
    recommendedTime: payload.recommendedTime,
    tags: payload.tags,
    fields: payload.fields,
  };
  const { data } = await apiClient.post<Favorite>("/favorites", body);
  // Coerce createdAt back to Date for client type safety
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

const PROFILE_PREVIEW_LIMIT = 6;
const COLLECTION_PAGE_SIZE = 12;

export async function getFavorites(
  categoryId?: string,
): Promise<Favorite[]> {
  const params = categoryId ? { categoryId } : undefined;
  const { data } = await apiClient.get<Favorite[]>("/favorites", { params });
  return data.map((fav) => ({
    ...fav,
    createdAt: new Date(fav.createdAt),
  }));
}

export type FavoritesPageResponse = {
  items: Favorite[];
  hasMore: boolean;
  nextOffset: number;
};

/** Paginated favorites for owner collection page (infinite scroll). */
export async function getFavoritesPage(
  offset: number,
  categoryId?: string,
  search?: string,
): Promise<FavoritesPageResponse> {
  const params: Record<string, string> = {
    limit: String(COLLECTION_PAGE_SIZE),
    offset: String(offset),
  };
  if (categoryId) params.categoryId = categoryId;
  if (search?.trim()) params.q = search.trim();
  const { data } = await apiClient.get<FavoritesPageResponse>("/favorites", {
    params,
  });
  return {
    items: (data.items ?? []).map((fav) => ({
      ...fav,
      createdAt: new Date(fav.createdAt),
    })),
    hasMore: data.hasMore ?? false,
    nextOffset: data.nextOffset ?? offset + (data.items?.length ?? 0),
  };
}

export { PROFILE_PREVIEW_LIMIT, COLLECTION_PAGE_SIZE };

export async function getFavorite(id: string): Promise<Favorite> {
  const { data } = await apiClient.get<Favorite>(`/favorites/${id}`);
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

export type UpdateFavoritePayload = Partial<
  Omit<Favorite, "id" | "userId" | "createdAt">
>;

export async function updateFavorite(
  id: string,
  payload: UpdateFavoritePayload,
): Promise<Favorite> {
  const { data } = await apiClient.patch<Favorite>(`/favorites/${id}`, payload);
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

export async function deleteFavorite(id: string): Promise<void> {
  await apiClient.delete(`/favorites/${id}`);
}

export async function uploadFavoriteMusic(
  id: string,
  file: File,
): Promise<Favorite> {
  // Upload directly browser → Cloudinary (resource_type "video" accepts audio files too)
  const musicUrl = await uploadToCloudinary(file, "video", "taste-tapestry/music");

  // Persist only the resulting URL to the backend
  const { data } = await apiClient.patch<Favorite>(`/favorites/${id}`, {
    fields: { musicUrl },
  });
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}


export async function getFavoriteLove(
  id: string,
): Promise<{ loved: boolean; count: number }> {
  const { data } = await apiClient.get<{ loved: boolean; count: number }>(
    `/favorites/${id}/love`,
  );
  return data;
}

export async function toggleFavoriteLove(
  id: string,
): Promise<{ loved: boolean; count: number }> {
  const { data } = await apiClient.post<{ loved: boolean; count: number }>(
    `/favorites/${id}/love`,
  );
  return data;
}

