import { apiClient } from "@/lib/api-client";
import { uploadToCloudinary } from "@/lib/upload";
import type { Favorite } from "@/types/wishbook";

export type CreateFavoritePayload = Omit<
  Favorite,
  "id" | "userId" | "createdAt"
> & {
  // createdAt is generated by backend; we don't send it
  createdAt?: never;
};

export async function createFavorite(
  payload: CreateFavoritePayload,
): Promise<Favorite> {
  const body = {
    categoryId: payload.categoryId,
    title: payload.title,
    image: payload.image,
    rating: payload.rating,
    mood: payload.mood,
    whyILike: payload.whyILike,
    timePeriod: payload.timePeriod,
    recommendedTime: payload.recommendedTime,
    tags: payload.tags,
    fields: payload.fields,
    status: payload.status,
  };
  const { data } = await apiClient.post<Favorite>("/favorites", body);
  // Coerce createdAt back to Date for client type safety
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

const PROFILE_PREVIEW_LIMIT = 6;
const COLLECTION_PAGE_SIZE = 15;

export async function getFavorites(
  categoryId?: string,
): Promise<Favorite[]> {
  const params = categoryId ? { categoryId } : undefined;
  const { data } = await apiClient.get<Favorite[]>("/favorites", { params });
  return data.map((fav) => ({
    ...fav,
    createdAt: new Date(fav.createdAt),
  }));
}

export type FavoritesPageResponse = {
  items: Favorite[];
  hasMore: boolean;
  nextOffset: number;
};

/** Paginated favorites for owner collection page (infinite scroll). */
export async function getFavoritesPage(
  offset: number,
  categoryId?: string,
  search?: string,
  sortBy: 'newest' | 'oldest' | 'rating_desc' | 'rating_asc' = 'newest',
  status?: string,
): Promise<FavoritesPageResponse> {
  const params: Record<string, string> = {
    limit: String(COLLECTION_PAGE_SIZE),
    offset: String(offset),
    sortBy,
  };
  if (categoryId) params.categoryId = categoryId;
  if (search?.trim()) params.q = search.trim();
  if (status && status !== 'all') params.status = status;
  const { data } = await apiClient.get<FavoritesPageResponse>("/favorites", {
    params,
  });
  return {
    items: (data.items ?? []).map((fav) => ({
      ...fav,
      createdAt: new Date(fav.createdAt),
    })),
    hasMore: data.hasMore ?? false,
    nextOffset: data.nextOffset ?? offset + (data.items?.length ?? 0),
  };
}

export { PROFILE_PREVIEW_LIMIT, COLLECTION_PAGE_SIZE };

/**
 * Mood-filtered public favorites for the /mood discovery pages.
 * Backend uses `mood && ARRAY[:moods]` overlap (GIN-indexed). Empty moods
 * returns the newest published favorites.
 */
export async function getFavoritesByMoods(
  offset: number,
  moods: string[],
  limit: number = COLLECTION_PAGE_SIZE,
  sortBy: 'newest' | 'oldest' | 'rating_desc' | 'rating_asc' = 'newest',
  scope?: 'all' | 'mine',
): Promise<FavoritesPageResponse> {
  const params: Record<string, string> = {
    limit: String(limit),
    offset: String(offset),
    sortBy,
  };
  const cleaned = moods.map((m) => m.trim()).filter(Boolean);
  if (cleaned.length > 0) params.moods = cleaned.join(',');
  if (scope === 'mine') params.scope = 'mine';
  const { data } = await apiClient.get<FavoritesPageResponse>('/favorites', {
    params,
  });
  return {
    items: (data.items ?? []).map((fav) => ({
      ...fav,
      createdAt: new Date(fav.createdAt),
    })),
    hasMore: data.hasMore ?? false,
    nextOffset: data.nextOffset ?? offset + (data.items?.length ?? 0),
  };
}

/**
 * Blind-recommendation roulette. Returns a single random PUBLISHED favorite
 * from the public pool. Optional `exclude` keeps recent spins from
 * resurfacing during rapid clicks.
 */
export async function getRandomFavorite(
  exclude?: string[],
): Promise<Favorite | null> {
  const params: Record<string, string> = {};
  const cleaned = (exclude ?? []).map((s) => s.trim()).filter(Boolean);
  if (cleaned.length > 0) params.exclude = cleaned.join(",");
  const { data } = await apiClient.get<Favorite | null>("/favorites/random", {
    params,
  });
  if (!data) return null;
  return { ...data, createdAt: new Date(data.createdAt) };
}

export async function getFavorite(id: string): Promise<Favorite> {
  const { data } = await apiClient.get<Favorite>(`/favorites/${id}`);
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

export type UpdateFavoritePayload = Partial<
  Omit<Favorite, "id" | "userId" | "createdAt">
>;

export async function updateFavorite(
  id: string,
  payload: UpdateFavoritePayload,
): Promise<Favorite> {
  const { data } = await apiClient.patch<Favorite>(`/favorites/${id}`, payload);
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

export async function deleteFavorite(id: string): Promise<void> {
  await apiClient.delete(`/favorites/${id}`);
}

export async function uploadFavoriteMusic(
  id: string,
  file: File,
): Promise<Favorite> {
  // Upload directly browser → Cloudinary (resource_type "video" accepts audio files too)
  const media = await uploadToCloudinary(file, "video", "taste-tapestry/music");
  const musicUrl = media.original_url;

  // Persist only the resulting URL to the backend
  const { data } = await apiClient.patch<Favorite>(`/favorites/${id}`, {
    fields: { musicUrl },
  });
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

export async function trackFavoriteImpression(
  id: string,
): Promise<{ viewCount: number }> {
  const { data } = await apiClient.post<{ viewCount: number }>(
    `/favorites/${id}/view`,
  );
  return data;
}

export async function trackAnalyticsBatch(
  events: Array<{
    itemId: string;
    eventType: "impression" | "click";
    sessionId: string;
    source?: string;
    device?: string;
    platform?: string;
  }>
): Promise<void> {
  // Fire and forget
  await apiClient.post("/analytics/batch", { events });
}

/* ──────────────────────────────────────────────────────────────────────────
 * Recommendation system — ITEMS, not users.
 *
 * The "Sparkles" feed surfaces PUBLISHED favorites owned by people the
 * viewer follows. Each row pairs the item card with a denormalized owner
 * chip so the dropdown can render at a glance.
 *
 * Two flows:
 *   - System feed: weighted scoring across category match, owner mutuals,
 *     item rating, engagement, etc. (server-cached, 5-min buckets).
 *   - Manual: a viewer explicitly recommends a specific favorite (with
 *     an optional note). Composite UNIQUE prevents duplicates.
 *
 * The server is the source of truth for ranking; the client only renders.
 * ──────────────────────────────────────────────────────────────────────────
 */

export type RecommendationSource = "system" | "manual";

/** Owner chip — the user who published the favorite. */
export interface RecommendedOwnerCard {
  id: string;
  username: string;
  displayName: string;
  avatar?: string | null;
}

/** The favorite itself, shaped for the dropdown card. */
export interface RecommendedItemCard {
  id: string;
  title: string;
  image: string | null;
  categoryId: string;
  rating: number | null;
  whyILike?: string | null;
  createdAt: string;
}

export interface RecommendationItem {
  id: string;            // favoriteId
  score: number;
  rank: number;
  source: RecommendationSource;
  item: RecommendedItemCard;
  owner: RecommendedOwnerCard;
  manual: boolean;
  /** Most recent note left by any recommender (manual only). */
  recentNote?: string | null;
}

export interface RecommendationFeedResult {
  items: RecommendationItem[];
  cached?: boolean;
  debug?: Record<string, number>;
}

export async function getSystemRecommendations(
  params: { limit?: number; debug?: boolean; bust?: boolean } = {},
): Promise<RecommendationFeedResult> {
  const { data } = await apiClient.get<RecommendationFeedResult>(
    "/recommendations/feed",
    {
      params: {
        limit: params.limit,
        debug: params.debug ? 1 : undefined,
        fresh: params.bust ? 1 : undefined,
      },
    },
  );
  return data ?? { items: [] };
}

export interface PaginatedRecommendedItems {
  items: RecommendationItem[];
  hasMore: boolean;
  nextOffset: number;
}

/** Items recommended BY a given user (paginated). */
export async function getRecommendedByUser(
  userId: string,
  params: { limit?: number; offset?: number } = {},
): Promise<PaginatedRecommendedItems> {
  const { data } = await apiClient.get<{
    items: RecommendationItem[];
    hasMore?: boolean;
    nextOffset?: number;
  }>(`/recommendations/recommended-by/${userId}`, {
    params: { limit: params.limit, offset: params.offset },
  });
  const items = data?.items ?? [];
  return {
    items,
    hasMore: data?.hasMore ?? false,
    nextOffset: data?.nextOffset ?? (params.offset ?? 0) + items.length,
  };
}

/** Items the caller has recommended (paginated). */
export async function getRecommendationsByMe(
  params: { limit?: number; offset?: number } = {},
): Promise<PaginatedRecommendedItems> {
  const { data } = await apiClient.get<{
    items: RecommendationItem[];
    hasMore?: boolean;
    nextOffset?: number;
  }>(`/recommendations/given`, {
    params: { limit: params.limit, offset: params.offset },
  });
  const items = data?.items ?? [];
  return {
    items,
    hasMore: data?.hasMore ?? false,
    nextOffset: data?.nextOffset ?? (params.offset ?? 0) + items.length,
  };
}

export interface ItemRecommenderRow {
  user: RecommendedOwnerCard;
  createdAt: string;
  note: string | null;
}

export async function getRecommendersForItem(
  favoriteId: string,
  params: { limit?: number; offset?: number } = {},
): Promise<{ items: ItemRecommenderRow[]; hasMore: boolean; nextOffset: number }> {
  const { data } = await apiClient.get<{
    items: ItemRecommenderRow[];
    hasMore?: boolean;
    nextOffset?: number;
  }>(`/recommendations/for-item/${favoriteId}`, {
    params: { limit: params.limit, offset: params.offset },
  });
  const items = data?.items ?? [];
  return {
    items,
    hasMore: data?.hasMore ?? false,
    nextOffset: data?.nextOffset ?? (params.offset ?? 0) + items.length,
  };
}

/** Manually recommend an item. */
export async function manualRecommendFavorite(
  favoriteId: string,
  note?: string,
): Promise<{ id: string; recommenderId: string; favoriteId: string; note: string | null; createdAt: string }> {
  const { data } = await apiClient.post<{
    id: string;
    recommenderId: string;
    favoriteId: string;
    note: string | null;
    createdAt: string;
  }>("/recommendations/manual", { favoriteId, note });
  return data;
}

/** Remove my manual recommendation for an item. */
export async function unmanualRecommendFavorite(
  favoriteId: string,
): Promise<void> {
  await apiClient.delete(`/recommendations/manual/${favoriteId}`);
}

export interface ItemRecommendationStats {
  favoriteId: string;
  count: number;
  topRecommenders: RecommendedOwnerCard[];
}

export async function getItemRecommendationStats(
  favoriteId: string,
  topLimit: number = 5,
): Promise<ItemRecommendationStats> {
  const { data } = await apiClient.get<ItemRecommendationStats>(
    `/recommendations/stats/${favoriteId}`,
    { params: { topLimit } },
  );
  return data;
}
