import { apiClient } from "@/lib/api-client";
import type { Favorite } from "@/types/wishbook";

export type CreateFavoritePayload = Omit<
  Favorite,
  "id" | "userId" | "createdAt"
> & {
  // createdAt is generated by backend; we don't send it
  createdAt?: never;
};

export async function createFavorite(
  payload: CreateFavoritePayload,
): Promise<Favorite> {
  const body = {
    categoryId: payload.categoryId,
    title: payload.title,
    image: payload.image,
    rating: payload.rating,
    mood: payload.mood,
    whyILike: payload.whyILike,
    timePeriod: payload.timePeriod,
    recommendedTime: payload.recommendedTime,
    tags: payload.tags,
    fields: payload.fields,
  };
  const { data } = await apiClient.post<Favorite>("/favorites", body);
  // Coerce createdAt back to Date for client type safety
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

export async function getFavorites(
  categoryId?: string,
): Promise<Favorite[]> {
  const params = categoryId ? { categoryId } : undefined;
  const { data } = await apiClient.get<Favorite[]>("/favorites", { params });
  return data.map((fav) => ({
    ...fav,
    createdAt: new Date(fav.createdAt),
  }));
}

export async function getFavorite(id: string): Promise<Favorite> {
  const { data } = await apiClient.get<Favorite>(`/favorites/${id}`);
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

export type UpdateFavoritePayload = Partial<
  Omit<Favorite, "id" | "userId" | "createdAt">
>;

export async function updateFavorite(
  id: string,
  payload: UpdateFavoritePayload,
): Promise<Favorite> {
  const { data } = await apiClient.patch<Favorite>(`/favorites/${id}`, payload);
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

export async function deleteFavorite(id: string): Promise<void> {
  await apiClient.delete(`/favorites/${id}`);
}

export async function uploadFavoriteMusic(
  id: string,
  file: File,
): Promise<Favorite> {
  const formData = new FormData();
  formData.append("file", file);
  const { data } = await apiClient.post<Favorite>(
    `/favorites/${id}/music`,
    formData,
    {
      headers: { "Content-Type": "multipart/form-data" },
    },
  );
  return {
    ...data,
    createdAt: new Date(data.createdAt),
  };
}

